/**
 * Implements hook_uninstall().
 */
function gt_sso_uninstall() {
  $module_list = array('cas', 'cas_attributes', 'externalauth');
  drupal_uninstall_modules($module_list, TRUE);

  // Remove any settings that the module has set.
  // Not sure which of these is the best in 10+ now
  \Drupal::configFactory()->getEditable('cas.settings')->delete();
  \Drupal::state()->delete('cas.settings');
  \Drupal::state()->delete('cas_attributes.settings');
}
